[package]
name = "lab_07"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rss = "2.0.0"
atom_syndication = "0.11.0"
reqwest = "0.11.6"
tokio = { version = "1.15.0", features = ["full"] }