//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lab_04_NoProxy.SimplexRef {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="A", Namespace="http://BPV/")]
    [System.SerializableAttribute()]
    public partial class A : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SField;
        
        private int KField;
        
        private float FField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string S {
            get {
                return this.SField;
            }
            set {
                if ((object.ReferenceEquals(this.SField, value) != true)) {
                    this.SField = value;
                    this.RaisePropertyChanged("S");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=1)]
        public int K {
            get {
                return this.KField;
            }
            set {
                if ((this.KField.Equals(value) != true)) {
                    this.KField = value;
                    this.RaisePropertyChanged("K");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public float F {
            get {
                return this.FField;
            }
            set {
                if ((this.FField.Equals(value) != true)) {
                    this.FField = value;
                    this.RaisePropertyChanged("F");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://BPV/", ConfigurationName="SimplexRef.SimplexSoap")]
    public interface SimplexSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://BPV/Add", ReplyAction="*")]
        int Add(int x, int y);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://BPV/Add", ReplyAction="*")]
        System.Threading.Tasks.Task<int> AddAsync(int x, int y);
        
        // CODEGEN: Generating message contract since element name s from namespace http://BPV/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://BPV/Concat", ReplyAction="*")]
        Lab_04_NoProxy.SimplexRef.ConcatResponse Concat(Lab_04_NoProxy.SimplexRef.ConcatRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://BPV/Concat", ReplyAction="*")]
        System.Threading.Tasks.Task<Lab_04_NoProxy.SimplexRef.ConcatResponse> ConcatAsync(Lab_04_NoProxy.SimplexRef.ConcatRequest request);
        
        // CODEGEN: Generating message contract since element name a1 from namespace http://BPV/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://BPV/Sum", ReplyAction="*")]
        Lab_04_NoProxy.SimplexRef.SumResponse Sum(Lab_04_NoProxy.SimplexRef.SumRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://BPV/Sum", ReplyAction="*")]
        System.Threading.Tasks.Task<Lab_04_NoProxy.SimplexRef.SumResponse> SumAsync(Lab_04_NoProxy.SimplexRef.SumRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://BPV/AddS", ReplyAction="*")]
        int AddS(int a, int b);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://BPV/AddS", ReplyAction="*")]
        System.Threading.Tasks.Task<int> AddSAsync(int a, int b);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ConcatRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Concat", Namespace="http://BPV/", Order=0)]
        public Lab_04_NoProxy.SimplexRef.ConcatRequestBody Body;
        
        public ConcatRequest() {
        }
        
        public ConcatRequest(Lab_04_NoProxy.SimplexRef.ConcatRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://BPV/")]
    public partial class ConcatRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string s;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public double d;
        
        public ConcatRequestBody() {
        }
        
        public ConcatRequestBody(string s, double d) {
            this.s = s;
            this.d = d;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ConcatResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ConcatResponse", Namespace="http://BPV/", Order=0)]
        public Lab_04_NoProxy.SimplexRef.ConcatResponseBody Body;
        
        public ConcatResponse() {
        }
        
        public ConcatResponse(Lab_04_NoProxy.SimplexRef.ConcatResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://BPV/")]
    public partial class ConcatResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string ConcatResult;
        
        public ConcatResponseBody() {
        }
        
        public ConcatResponseBody(string ConcatResult) {
            this.ConcatResult = ConcatResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SumRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Sum", Namespace="http://BPV/", Order=0)]
        public Lab_04_NoProxy.SimplexRef.SumRequestBody Body;
        
        public SumRequest() {
        }
        
        public SumRequest(Lab_04_NoProxy.SimplexRef.SumRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://BPV/")]
    public partial class SumRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Lab_04_NoProxy.SimplexRef.A a1;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public Lab_04_NoProxy.SimplexRef.A a2;
        
        public SumRequestBody() {
        }
        
        public SumRequestBody(Lab_04_NoProxy.SimplexRef.A a1, Lab_04_NoProxy.SimplexRef.A a2) {
            this.a1 = a1;
            this.a2 = a2;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SumResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SumResponse", Namespace="http://BPV/", Order=0)]
        public Lab_04_NoProxy.SimplexRef.SumResponseBody Body;
        
        public SumResponse() {
        }
        
        public SumResponse(Lab_04_NoProxy.SimplexRef.SumResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://BPV/")]
    public partial class SumResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Lab_04_NoProxy.SimplexRef.A SumResult;
        
        public SumResponseBody() {
        }
        
        public SumResponseBody(Lab_04_NoProxy.SimplexRef.A SumResult) {
            this.SumResult = SumResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface SimplexSoapChannel : Lab_04_NoProxy.SimplexRef.SimplexSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SimplexSoapClient : System.ServiceModel.ClientBase<Lab_04_NoProxy.SimplexRef.SimplexSoap>, Lab_04_NoProxy.SimplexRef.SimplexSoap {
        
        public SimplexSoapClient() {
        }
        
        public SimplexSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SimplexSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SimplexSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SimplexSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public int Add(int x, int y) {
            return base.Channel.Add(x, y);
        }
        
        public System.Threading.Tasks.Task<int> AddAsync(int x, int y) {
            return base.Channel.AddAsync(x, y);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Lab_04_NoProxy.SimplexRef.ConcatResponse Lab_04_NoProxy.SimplexRef.SimplexSoap.Concat(Lab_04_NoProxy.SimplexRef.ConcatRequest request) {
            return base.Channel.Concat(request);
        }
        
        public string Concat(string s, double d) {
            Lab_04_NoProxy.SimplexRef.ConcatRequest inValue = new Lab_04_NoProxy.SimplexRef.ConcatRequest();
            inValue.Body = new Lab_04_NoProxy.SimplexRef.ConcatRequestBody();
            inValue.Body.s = s;
            inValue.Body.d = d;
            Lab_04_NoProxy.SimplexRef.ConcatResponse retVal = ((Lab_04_NoProxy.SimplexRef.SimplexSoap)(this)).Concat(inValue);
            return retVal.Body.ConcatResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Lab_04_NoProxy.SimplexRef.ConcatResponse> Lab_04_NoProxy.SimplexRef.SimplexSoap.ConcatAsync(Lab_04_NoProxy.SimplexRef.ConcatRequest request) {
            return base.Channel.ConcatAsync(request);
        }
        
        public System.Threading.Tasks.Task<Lab_04_NoProxy.SimplexRef.ConcatResponse> ConcatAsync(string s, double d) {
            Lab_04_NoProxy.SimplexRef.ConcatRequest inValue = new Lab_04_NoProxy.SimplexRef.ConcatRequest();
            inValue.Body = new Lab_04_NoProxy.SimplexRef.ConcatRequestBody();
            inValue.Body.s = s;
            inValue.Body.d = d;
            return ((Lab_04_NoProxy.SimplexRef.SimplexSoap)(this)).ConcatAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Lab_04_NoProxy.SimplexRef.SumResponse Lab_04_NoProxy.SimplexRef.SimplexSoap.Sum(Lab_04_NoProxy.SimplexRef.SumRequest request) {
            return base.Channel.Sum(request);
        }
        
        public Lab_04_NoProxy.SimplexRef.A Sum(Lab_04_NoProxy.SimplexRef.A a1, Lab_04_NoProxy.SimplexRef.A a2) {
            Lab_04_NoProxy.SimplexRef.SumRequest inValue = new Lab_04_NoProxy.SimplexRef.SumRequest();
            inValue.Body = new Lab_04_NoProxy.SimplexRef.SumRequestBody();
            inValue.Body.a1 = a1;
            inValue.Body.a2 = a2;
            Lab_04_NoProxy.SimplexRef.SumResponse retVal = ((Lab_04_NoProxy.SimplexRef.SimplexSoap)(this)).Sum(inValue);
            return retVal.Body.SumResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Lab_04_NoProxy.SimplexRef.SumResponse> Lab_04_NoProxy.SimplexRef.SimplexSoap.SumAsync(Lab_04_NoProxy.SimplexRef.SumRequest request) {
            return base.Channel.SumAsync(request);
        }
        
        public System.Threading.Tasks.Task<Lab_04_NoProxy.SimplexRef.SumResponse> SumAsync(Lab_04_NoProxy.SimplexRef.A a1, Lab_04_NoProxy.SimplexRef.A a2) {
            Lab_04_NoProxy.SimplexRef.SumRequest inValue = new Lab_04_NoProxy.SimplexRef.SumRequest();
            inValue.Body = new Lab_04_NoProxy.SimplexRef.SumRequestBody();
            inValue.Body.a1 = a1;
            inValue.Body.a2 = a2;
            return ((Lab_04_NoProxy.SimplexRef.SimplexSoap)(this)).SumAsync(inValue);
        }
        
        public int AddS(int a, int b) {
            return base.Channel.AddS(a, b);
        }
        
        public System.Threading.Tasks.Task<int> AddSAsync(int a, int b) {
            return base.Channel.AddSAsync(a, b);
        }
    }
}
